---
  - name: Docker
    hosts: all
    tasks:
      - name: Install Docker
        command: sudo yum install docker -y
      - name: Add to group
        command: sudo usermod -a -G docker ec2-user
      - name: Add to autostart
        command: sudo systemctl enable docker.service
      - name: Run
        command: sudo systemctl start docker.service
    
  - name: Init Swarm manager
    hosts: manager
    become: true
    tasks:
      - name: Swarm init
        command: docker swarm init --advertise-addr {{ inventory_hostname }}
        run_once: true

  - name: Install Portainer
    hosts: manager
    tasks:
      - name: Download
        command: curl -L https://downloads.portainer.io/portainer-agent-stack.yml -o portainer-agent-stack.yml
      - name: Deploy
        command: docker stack deploy -c portainer-agent-stack.yml portainer

  - name: Get swarm join tokens
    hosts: manager
    become: true
    tasks:
      - name: Get worker token
        command: docker swarm join-token worker -q
        register: worker_token
      - name: Print worker token
        debug: var=worker_token.stdout
      - name: Get manager token
        command: docker swarm join-token manager -q
        register: manager_token
      - name: Print manager token
        debug: var=manager_token.stdout


  - name: Join workers to swarm cluster
    hosts: workers
    become: true
    vars:
      token: "{{hostvars[groups['manager'][0]]['worker_token']['stdout']}}"
      manager: "{{hostvars[groups['manager'][0]]['inventory_hostname']}}"
    tasks:
      - name: Join
        command: sudo docker swarm join --token {{ token }} {{ manager }}:2377
        register: worker
      - name: Result
        debug: var=worker.stdout
      - name: Error
        debug: var=worker.stderr
